SRC = bsq.c find_solution.c functions.c ft_get_chars.c print_solution.c ft_read_map.c ft_verif_map.c

all:
	cc -Wall -Wextra -Werror $(SRC) -o bsq
	
clean:
	rm -f *.o

fclean: clean
	rm -f bsq
	
re: fclean all
