SRC = bsq.c ft_print_solution.c ft_find_solution.c ft_verif_map.c ft_read_map.c ft_get_chars.c functions.c

all:
	cc -Wall -Wextra -Werror -o bsq $(SRC)
	
clean:
	rm -f *.o

fclean: clean
	rm -f bsq
	
re: fclean all
